### ISSUE TITLE
MPS support

### ISSUE THREAD

**Issue by hdavid16** [APMonitor/apopt#1]
I'm looking at ways that apopt can be integrated with JuMP on Julia. I can write .lp or .mps files easily from JuMP. Does apopt support these file formats?

**Comment by APMonitor** [comment]
APOPT has an interface to nl files (AMPL and Pyomo) and to APMonitor / Gekko. There is an APMonitor (and APOPT) interface to Julia but it was created with an older version of Julia and may not be functional with 1.0+: https://github.com/APMonitor/apm_julia  The .lp and .mps files only support linear programming problems so it wouldn't allow the full range of MINLP problems that APOPT can support. Let me know if you do fix up the APMonitor / APOPT interface to Julia.

**Comment by hdavid16** [comment]
Ok. I may end up looking to write a wrapper for APOPT in the future to call it from JuMP as was done for the NEOS server. https://github.com/odow/NEOS.jl. Thanks
