### ISSUE TITLE
Error: Bad function value, Equation(1) residual not computed.

### ISSUE THREAD

**Issue by martinkoutecky** [APMonitor/apopt#3]
Hi,
I've tried to use apopt.py, but the solver seems to bail with many error  messages like this one:

`* Error: Bad function value, Equation(1) residual not computed.`

(Seems to return this for all equations.) I don't really know what this means, and also no other solver has an issue with my model, so it seems like an apopt issue. Any ideas?

**Comment by APMonitor** [comment]
There is likely a NaN evaluation that APOPT evaluates on the way to the solution. A variable bound (constraints) can help avoid things like divide-by-zero. There are better APOPT solver reporting options in Gekko if you want to try that as well: https://apmonitor.com/wiki/index.php/Main/GekkoPythonOptimization

**Comment by martinkoutecky** [comment]
Hm. I'm using pyomo and trying to figure out the best solver for my model (because I want to solve a lot of models of this type). If I understand correctly, to use gekko, I'd have to describe the model in gekko instead of pyomo, and that's a lot of work I'd rather avoid.

All variables are continuous `UnitInterval`, so they have bounds. What else could I try? Do I need to add these somehow explicitly as bounds? (I though pyomo does that, but maybe not?)

**Comment by APMonitor** [comment]
Yes, stay with pyomo if your model is already described there. We've worked in pyomo and other modeling languages. Gekko was about 5x faster for the large-scale problems we were solving. Here is information on setting bounds with Pyomo: https://pyomo.readthedocs.io/en/stable/pyomo_modeling_components/Variables.html  Use the bounds=(1e-5,10) argument when defining the variable such as for `y = 1/x` to avoid divide-by-zero for a value of `x=0`.
