### ISSUE TITLE
HTTPError

### ISSUE THREAD

**Issue by farhadbl** [APMonitor/apopt#4]
I am getting an error in request.py that req.full_url link does not exist:

'http://byu.apopt.com/online/73.67.165.9_varfolderszdd2yjy2wx0gqfbt673w4gn980000gnttmpnn5toy3pyomo/73.67.165.9_varfolderszdd2yjy2wx0gqfbt673w4gn980000gnttmpnn5toy3pyomo.sol' 

def http_error_default(self, req, fp, code, msg, hdrs):
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

I am able to successfully run apopt.py -test

**Comment by APMonitor** [comment]
The `APOPT` solver is a web service that solves the model on the remote server https://byu.apopt.com The `.nl` file is sent to the server and the server returns the `.sol` that is then processed by pyomo for the solution. When the link does not exist, it means that the computer either has a problem with the connection to the server or else the solver failed to find a solution. Maybe try it with a simple optimization problem to make sure a solution can be returned.
